# -*- coding: utf-8 -*-
"""Copy of Pandas-Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-kbbecXJmX2oKwxrqoZ9lJy84z_TL9nG

## Part 1

Task 1 : import the CSV file data/brasil-real-estate-1.csv into dataframe df
"""

import pandas as pd
df = pd.read_csv('/content/brasil-real-estate-1.csv', encoding='ISO-8859-1')
df

"""Task 2 :Drop all rows with NAN values from df"""

# df = df.dropna(axis=0 , how='all' , inplace=True)

"""Task 3: use "lat-lon" columns to create two seperate columns in df "lat", "lon". make sure that the datatype will be float"""

df[['lat','lon']] = df['lat-lon'].apply(lambda x: pd.Series(str(x).split(","))).astype(float)
print(df.dtypes)

"""Task 4: Transform "price_USD" so that all values be floating points instead of strigns"""

df[['$','price1_USD']] = df['price_usd'].apply(lambda x: pd.Series(str(x).split('$')))
print(df.dtypes)

df = df.drop('price_usd' , axis=1)
df = df.drop('$' , axis=1)
df

df = df.rename(columns={'price1_USD':'price_USD'})
df

"""Task 5: drop "lat-lon" columns"""

df = df.drop('lat-lon' , axis=1)
df

"""Task 6: import the CSV file data/brasil-real-estate-2.csv into dataframe df2"""

df2 = pd.read_csv('/content/brasil-real-estate-2.csv' , encoding='ISO-8859-1')
df2

"""Task 7: use "price_berl" to create new columns named "price_usd" by dividing the value by 3.19"""

print(df2.dtypes)

df2[['price_usd']] = df2[['price_brl']].div(3.19)
df2

"""Task 8: drop "price_berl" from columns, as well as any rows that have Nan values"""



"""Task 9: concatenate df and df2 into new dataframe named df_new"""

df_con =[df,df2]
df_new = pd.concat(df_con)
df_new

""":Task 10: use describe method to create dataframe summary_stats for "area_m2" and "price_usd" columns"""

# df_new.dtypes
summary_stats = df_new[['area_m2','price_USD']].describe(include = 'all')
summary_stats

"""Task 11: use groupby method to create a series named mean_price_by_region that shows the mean home price in brazil, sorted from smallest to highest"""

brazil_df = df_new[df_new['place_with_parent_names']=='|Brasil|Alagoas|Maceió|']
brazil_df

mean_price_by_region  =  brazil_df[['place_with_parent_names','price_USD']].groupby('price_USD').mean() 
mean_price_by_region

"""Task 12: create new dataframe named df_south that contains all homes from df in South region"""

df_south = df_new[df_new['region']=='South']
df_south

"""Task 13: use value_counts method to ctreate a series home_by_state that contains the number of properties in df_south"""



"""## Part 2

Task 14: Write a wrangle function that takes the name of csv as argument and perform the following : 

1- read mexico-real-estate-1.csv into df 

2- get only the apartment that locates in mexico city "Distrito Federal" that costs less than 100,000

3- create seperate "lat" and "lon" columns as done before

4- drop columns that are more than 50 % Nan values

5- drop all columns with categorical values

6- return df at last
"""

# -----------------> 1
def read_data(file_path: str) -> pd.DataFrame: 
  df = pd.read_csv(file_path ,encoding='ISO-8859-1')
#------------------> 2
  df['price_usd'] = df['price_usd'].apply(lambda x: str(x.split()[0].replace('$', '')))
  df['price_usd'] = df['price_usd'].apply(lambda x: float(x.split()[0].replace(',', '')))
  get_Distrito_Federal = df[(df['state']=='Distrito Federal') & (df['price_usd']<100000)]
  # return get_Distrito_Federal
# 3 -------> already exists in file cxv
# ----------------->4
  for col in df:
    if df[col].isnull().sum() / df[col].size > .5:
      df.drop([col], axis=1)
  

  
 
  
read_data('/content/mexico-real-estate-1.csv')

"""use glob method to create list of files. it should contains the filename of all mexico real state. """



"""combine your wrangle function, a list comprehnsion and pd.concat to create new dataframe df from all files names from previous task"""

